title: "GHPF Lab"
description: "Greenhouse Horticulture and Plant Factory Lab — Seoul National University"

url: "https://snughpf-alt.github.io"
baseurl: "/ghpf-lab-web-final-2"

author: "Tae In Ahn"
email: "tiahn@snu.ac.kr"
timezone: "Asia/Seoul"
lang: "en"

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
